### PR TITLE
Updated OpenCV and others

### PR DESCRIPTION
**Pull request by keithjjones**
Updated to OpenCV 3.1.  Added a library dependency that was missing.  Updated .gitignore file.  Updated wxWidgets.

### CODE REVIEW

**Comment by keithjjones** [comment]
Note that at this point everything works as expected.  The executable runs fine inside the CodeBlocks debugger.  However, starting the executable outside of the debugger on Win10 causes an initialization error.  Any ideas @andybarry?

I am looking into it, but my wxWidgets experience may not be as deep as yours.

**Comment by keithjjones** [comment]
The error I am experiencing is "The application was unable to start correctly (0xc000007b).  Click OK to close the application.  However, it runs perfectly fine if I start it in CodeBlocks debugger.

**Comment by keithjjones** [comment]
It appears as if I got the bug to disappear.  There was an issue with something to do with mixed 64-bit and 32-bit code.  I'm working on further testing.

**Comment by keithjjones** [comment]
Now it appears as if OpenCV can't connect to the camera.  I am at a loss as to why.  Every other application I've tried can see it.  I even tested OpenCV through Python and it can't see the camera.

**Comment by andybarry** [comment]
For a while you had to install separate drivers for the PS3 eye in Windows, but if other things can access it you should be OK.  Do you get an error messages when attempting to connect?

**Comment by keithjjones** [comment]
No.  OpenCV can't see it at all.  Even from Python.  I think the drivers are only supported with 32bit, which is a shame.  The world is much more 64-bit now.  I am trying the 32-bit version of everything, but it is requiring me to install 32-bit everything which is taking a bit because I do zero 32-bit development.

Windows 10 seems to detect it automatically, and I'm testing that version of the driver too.

**Comment by andybarry** [comment]
Ugg, 32 bit.  Let me know if I can help debug further.

**Comment by keithjjones** [comment]
Your toolchain was 32 bit when you created this, right?  I have everything running in 64 bit, but it won't detect the camera.

I can't even get the camera to detect using something like Skype on the same computer.  The Camera will work with the CL driver test app though.  Weird.

**Comment by andybarry** [comment]
Yes, the original code is from 2010, so definitely 32-bit in Windows.  64-bit in linux though.  We should still be able to compile it in 32bit mode, yes?

**Comment by keithjjones** [comment]
Yes, I got everything compiling in 64-bit with very few changes.  It's just not seeing the camera now.

**Comment by keithjjones** [comment]
PS - I would say hold off on this pull request.  When(if) I get this working the way we want it to, I will clean up my commit history and make a much nicer one for you.  I'll leave this one on until I get a new one, then I'll manually close this one.  I like to be tidier with my commits than this turned out to be.  You learn something new every day.

**Comment by andybarry** [comment]
OK sounds good.

**Comment by keithjjones** [comment]
While I have you here.... I'm 99% sure I have everything working fine in 64-bit on Windows.  The only hold back is the Eye camera drivers.  We may be able to side step a lot of pain with another camera, perhaps with higher resolution.  Do you know of any other cameras you recommend we could use in its place?  I don't mind making it work if you know of a good relatively inexpensive camera for the task.  Also, how did you calculate the FOV angles for the Eye?  Did you find a spec sheet?  Or did you measure them?

**Comment by keithjjones** [comment]
For example, PS Eye doesn't work with Skype 64-bit.  So I am pretty sure it is the camera.  It works with 32-bit apps somewhat, but it may be a bit dated.

**Comment by andybarry** [comment]
I measured them.  The biggest trouble with switching cameras would be that we'd need a new mount for it on the 3D printer side.  Maybe we can patch in updated drivers?  Do you happen to know if that driver is open source?

**Comment by keithjjones** [comment]
No, you had to buy the drivers.  And they are pretty old.  We may be able to ask them, but I don't know how that will go over.  Most of their postings and everything on their site says 2010-2013.

https://codelaboratories.com/

I don't mind making a new mount if we find a different camera.  I'm pretty handy in CAD.  I like Fusion360.  It's free and powerful.

How did you measure the values?

**Comment by keithjjones** [comment]
@ryanshuck is working on looking for code for the PS Eye we can make 64 bit.  I'm adding him to this thread.

**Comment by keithjjones** [comment]
@andybarry @ryanshuck I verified that PSEYE works through VMWare 11 with Linux as the guest, and Windows as the host, with the CL drivers on Windows.  I'm using Windows 10.  Maker scanner works perfectly.

**Comment by keithjjones** [comment]
@ryanshuck pointed this project out:  https://github.com/inspirit/PS3EYEDriver

**Comment by keithjjones** [comment]
I'm going to start over on this effort.  I have a couple of good ideas that I think will work.  Stay tuned.

**Pull request closed without merging**
